export const projects = [
  {
    company: "OpenCafe LLC",
    website: "https://opencafe.club/",
    desc: "Software Development Service Company (Nepal)",
    timeframe: "Dec 2022 - May 2024",
    title: "Senior Software Engineer",
    work: "Worked on frontend micro services, created component packages and documented them with Storybook. Developed PDF Template Generator with drag and drop features using React Konva and Shadcn UI. Worked on React Native app development focusing more on backend side using Golang and AWS Serverless.",
    tech: [
      "React Vite",
      "ReactQuery",
      "Next.js",
      "Storybook",
      "Jest",
      "MUI",
      "ShadcnUI",
      "MantineUI",
      "Github Actions",
      "Golang",
      "AWS",
    ],
  },
  {
    company: "Mercanto",
    website: "https://mercanto.mx/",
    desc: "B2b E-commerce Platform (Mexico)",
    timeframe: "Dec 2022 - Dec 2023",
    title: "Frontend Lead",
    work: "Responsible for leading a small team for building and transitioning a Shopify based B2B e-commerce platform into optimized web application. Includes reviewing pull requests and feature discussion meetings. For the most part, worked more on the provisioning side, splitting and building cross domain platforms integrating webbooks and openAPIs of Shopify giving it a modern touch.",
    tech: [
      "React Vite",
      "Next.js",
      "ReactQuery",
      "Hook Form",
      "Storybook",
      "Jest",
      "MUI",
      "Github Actions",
      "Google Maps",
      "PostHog",
      "GTM",
    ],
  },
  {
    company: "Varicon",
    website: "https://varicon.com.au/",
    desc: "Construction Cost Management Company (Australia)",
    timeframe: "Dec 2021 - Dec 2022",
    title: "React Developer",
    work: "Worked mainly on building reusable react components along with redux and contextAPI for managing complex array and object manipulations.",
    tech: ["React CRA", "ContextAPI", "Redux", "Hook Form", "MUI"],
  },
  {
    company: "Virtuosway (Previously EeposIT)",
    website: "https://www.virtuosway.com/",
    project: "https://www.appyhere.com/",
    desc: "Software Service Company (Nepal)",
    timeframe: "Dec 2020 - Dec 2021",
    title: "React Developer",
    work: "Participated in a project called AppyHere, where I was responsible for developing new features, conducting unit tests, and maintaining existing code alongside the team.",
    tech: [
      "React CRA",
      "ContextAPI",
      "Firebase",
      "Hook Form",
      "ChakraUI",
      "Jest",
      "Twilio",
    ],
  },
  {
    company: "Auxfin",
    website: "https://www.auxfin.com/",
    desc: "Financial and Social Inclusion for developing countries in Africa",
    timeframe: "April 2016 - Jan 2020",
    title: "Junior FullStack Developer",
    work: "Worked on multiple projects, implementing full-stack development to create robust applications.",
    tech: [
      "JS / AJAX / JQuery",
      "React / React Native",
      "Redux",
      "Laravel / PHP",
      "MySQL",
      "Bootstrap",
      "Reactstrap",
      "Joomla",
    ],
  },
];
